"""V3 package manifest and content hashes (G5-PKG-001)."""

from .manifest import (
    FINGERPRINT_POLICY_VERSION,
    PACKAGE_BUILDER_VERSION,
    build_package_manifest,
    detect_runtime,
    semantic_fingerprint_for_path,
)
from .verify import (
    PACKAGE_MANIFEST_SCHEMA_PATH,
    validate_manifest_schema,
    verify_package_manifest,
)
from .bom import (
    BOM_BUILDER_VERSION,
    BOM_COLUMNS,
    BOM_SCHEMA_PATH,
    build_bom,
    validate_bom_schema,
    verify_bom,
)
from .drawing import (
    DEFAULT_TOLERANCE,
    DEFAULT_VIEW_SCALE,
    DEFAULT_WHITELIST,
    DRAWING_BUILDER_VERSION,
    DRAWING_SCHEMA_PATH,
    DRAWING_TEMPLATE_VERSION,
    NOT_FOR_MANUFACTURING,
    WATERMARK,
    build_draft_drawing,
    qa_all_passed,
    validate_drawing_schema,
    verify_draft_drawing,
)
from .repro import (
    REPRO_ARTIFACT_NAMES,
    REPRO_BYTE_STABLE,
    REPRO_BUILDER_VERSION,
    build_fingerprint_report,
    compare_to_golden,
    rebuild_prototype_outputs,
    validate_golden,
)

__all__ = [
    "FINGERPRINT_POLICY_VERSION",
    "PACKAGE_BUILDER_VERSION",
    "PACKAGE_MANIFEST_SCHEMA_PATH",
    "BOM_BUILDER_VERSION",
    "BOM_COLUMNS",
    "BOM_SCHEMA_PATH",
    "build_package_manifest",
    "detect_runtime",
    "semantic_fingerprint_for_path",
    "validate_manifest_schema",
    "verify_package_manifest",
    "build_bom",
    "validate_bom_schema",
    "verify_bom",
    "DEFAULT_TOLERANCE",
    "DEFAULT_VIEW_SCALE",
    "DEFAULT_WHITELIST",
    "DRAWING_BUILDER_VERSION",
    "DRAWING_SCHEMA_PATH",
    "DRAWING_TEMPLATE_VERSION",
    "NOT_FOR_MANUFACTURING",
    "WATERMARK",
    "build_draft_drawing",
    "qa_all_passed",
    "validate_drawing_schema",
    "verify_draft_drawing",
    "REPRO_ARTIFACT_NAMES",
    "REPRO_BYTE_STABLE",
    "REPRO_BUILDER_VERSION",
    "build_fingerprint_report",
    "compare_to_golden",
    "rebuild_prototype_outputs",
    "validate_golden",
]
