import { AlertTriangle, Box, CheckCircle2, CircleHelp, FileX2, RotateCcw } from "lucide-react";
import type { DemoResult } from "../types/prototype";

export function ResultsPage({ result, onRestart }: { result: DemoResult; onRestart: () => void }) {
  return <><section className="page-heading compact"><div><p className="eyebrow">合成展示資料 · Synthetic demo data</p><h1>參考治具結果預覽</h1><p>此頁只驗證資訊架構與操作流程，不能用於工程或製造。</p></div><span className="prototype-badge danger">未產生任何工程製品 · No engineering artifact generated</span></section>
    <section className="result-hero panel"><div className="result-visual"><svg viewBox="0 0 520 330" role="img"><title>治具展示示意圖，不是 CAD</title><defs><linearGradient id="face" x1="0" x2="1"><stop stopColor="#15383b"/><stop offset="1" stopColor="#0b2025"/></linearGradient></defs><path className="top" d="m65 105 191-66 201 76-198 72Z"/><path className="side" d="M65 105v117l194 73 198-86v-94l-198 72Z"/><path className="detail" d="m119 112 137-47 145 54-142 51Z"/><path className="detail" d="M259 187v108M65 167l194 73 198-85"/><circle cx="111" cy="187" r="9"/><circle cx="401" cy="170" r="9"/></svg><div className="cad-watermark">示意圖<br/><strong>非 CAD</strong></div></div><div className="result-summary"><span className="status-pill active">{result.maturity}</span><h2>治具／電子外殼</h2><dl><div><dt>外形</dt><dd>{result.dimensions}</dd></div><div><dt>材料</dt><dd>{result.material} <small>展示預設</small></dd></div><div><dt>製程</dt><dd>{result.process} <small>展示預設</small></dd></div></dl><button className="secondary-action" onClick={onRestart}><RotateCcw size={17}/>返回設計</button></div></section>
    <section className="result-grid"><article className="panel result-panel"><div className="panel-heading"><div><span className="panel-kicker">展示檢查</span><h2>規則結果資訊架構</h2></div><span>{result.checks.length} 筆記錄</span></div><div className="check-list">{result.checks.map((check) => <div key={check.name}>{check.state === "demo-pass" ? <CheckCircle2 className="ok" size={19}/> : <CircleHelp className="warn" size={19}/>}<span><strong>{check.name}</strong><small>{check.note}</small></span><em>{check.state === "demo-pass" ? "展示通過" : "需要檢視"}</em></div>)}</div></article><article className="panel result-panel"><div className="panel-heading"><div><span className="panel-kicker">展示物料表</span><h2>物料表資訊架構</h2></div><span>{result.bom.length} 筆記錄</span></div><div className="bom-list">{result.bom.map((item) => <div key={item.item}><Box size={18}/><span><strong>{item.item}</strong><small>{item.note}</small></span><em>× {item.quantity}</em></div>)}</div></article></section>
    <section className="unavailable-artifacts"><FileX2 size={21}/><div><strong>刻意停用工程製品下載</strong><span>STEP、圖面 PDF、BOM CSV 與 release_manifest.json 要等 G2–G5 產生真實證據。</span></div><AlertTriangle size={20}/></section></>;
}
