import { AlertTriangle, Box, CircleHelp, FileX2, RotateCcw } from "lucide-react";
import type { IrDraftResponse } from "../types/guidance";

export function ResultsPage({ draft, onRestart }: { draft: IrDraftResponse | null; onRestart: () => void }) {
  if (!draft) return <section className="panel acknowledge-card"><h1>尚無可顯示的 IR 草稿</h1><p>結果頁不會建立替代或合成資料。</p><button className="secondary-action" onClick={onRestart}><RotateCcw size={17}/>返回設計</button></section>;
  const { document, correlationId, contentSha256 } = draft;
  const dimensions = document.components.flatMap((component) => component.dimensions.map((dimension) => `${dimension.name}: ${dimension.quantity.nominal ?? "?"} ${dimension.quantity.unit}`));
  return <>
    <section className="page-heading compact"><div><p className="eyebrow">本機工程 API 回應</p><h1>IR 草稿結果</h1><p>此頁呈現版本化資料結構與可追溯未知項目，不能用於製造。</p></div><span className="prototype-badge danger">DRAFT IR only · No engineering artifact generated</span></section>
    <section className="result-hero panel"><div className="result-visual"><svg viewBox="0 0 520 330" role="img"><title>治具概念示意圖，不是 CAD</title><path className="top" d="m65 105 191-66 201 76-198 72Z"/><path className="side" d="M65 105v117l194 73 198-86v-94l-198 72Z"/><path className="detail" d="m119 112 137-47 145 54-142 51Z"/></svg><div className="cad-watermark">示意圖<br/><strong>非 CAD</strong></div></div><div className="result-summary"><span className="status-pill active">{document.maturity}</span><h2>{document.designId}</h2><dl><div><dt>Schema</dt><dd>{document.schemaVersion}</dd></div><div><dt>Revision</dt><dd>{document.revision}</dd></div><div><dt>Correlation ID</dt><dd>{correlationId}</dd></div><div><dt>Response SHA-256</dt><dd>{contentSha256}</dd></div></dl><button className="secondary-action" onClick={onRestart}><RotateCcw size={17}/>返回設計</button></div></section>
    <section className="result-grid"><article className="panel result-panel"><div className="panel-heading"><div><span className="panel-kicker">IR components</span><h2>元件與尺寸</h2></div><span>{document.components.length} 個元件</span></div><div className="bom-list">{document.components.map((item) => <div key={item.id}><Box size={18}/><span><strong>{item.name}</strong><small>{item.componentType}</small></span></div>)}{dimensions.map((value) => <div key={value}><Box size={18}/><span><strong>{value}</strong></span></div>)}</div></article><article className="panel result-panel"><div className="panel-heading"><div><span className="panel-kicker">未解決事項</span><h2>Unknowns</h2></div><span>{document.unknowns.length} 筆</span></div><div className="check-list">{document.unknowns.map((item) => <div key={item.id}><CircleHelp className="warn" size={19}/><span><strong>{item.field}</strong><small>{item.question}</small></span><em>{item.unsafeToDefault ? "不可預設" : "待確認"}</em></div>)}</div></article></section>
    <section className="unavailable-artifacts"><FileX2 size={21}/><div><strong>工程製品功能尚未接入此控制面</strong><span>沒有 STEP、圖面、BOM CSV 或 release manifest 下載；此段只建立 DRAFT IR。</span></div><AlertTriangle size={20}/></section>
  </>;
}
