import { AlertOctagon, ArrowLeft, ChevronRight, CircleHelp, Database, UserRound } from "lucide-react";
import { useState } from "react";
import type { PrototypeViewModel, Provenance } from "../types/prototype";

const labels: Record<Provenance, string> = { user: "使用者提供", "demo-derived": "Demo 衍生", "demo-default": "Demo 預設", unknown: "未知" };
export function ReviewPage({ model, onBack, onRun }: { model: PrototypeViewModel; onBack: () => void; onRun: () => void }) {
  const [acknowledged, setAcknowledged] = useState(false);
  return <><section className="page-heading compact"><div><p className="eyebrow">ASSUMPTION REVIEW · STEP 2 OF 3</p><h1>生成前確認</h1><p>把事實、預設值與未知項目分開；critical unknown 不會被自動填入。</p></div><span className="prototype-badge">NO ENGINEERING ARTIFACT</span></section>
    <section className="review-layout"><div className="panel review-table"><div className="panel-heading"><div><span className="panel-kicker">INPUT TRACEABILITY</span><h2>輸入與來源</h2></div><span>{model.review.length} items</span></div>{model.review.map((item) => <div className={`review-row ${item.critical ? "critical" : ""}`} key={item.id}><div className={`provenance-icon ${item.provenance}`}>{item.provenance === "user" ? <UserRound size={17} /> : item.provenance === "unknown" ? <CircleHelp size={17} /> : <Database size={17} />}</div><div><strong>{item.label}</strong><span>{item.value}</span></div><em className={`provenance-tag ${item.provenance}`}>{labels[item.provenance]}</em></div>)}</div>
      <aside className="review-side"><article className="panel critical-card"><AlertOctagon size={22} /><div><span className="panel-kicker">UNSAFE TO DEFAULT</span><h2>PCB 詳細 envelope</h2><p>真實 CAD 生成前必須取得板框、零件高度、孔位及 keep-out。UI-0 不會猜測。</p></div></article><article className="panel acknowledge-card"><h2>原型界線</h2><ul><li>不執行 geometry kernel</li><li>不執行 CNC DFM rules</li><li>不產生 STEP、圖面或 package</li></ul><label className="check-row"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} /><span>我了解下一步只會執行 prototype simulation。</span></label><div className="action-row"><button className="secondary-action" onClick={onBack}><ArrowLeft size={17} />返回修改</button><button className="primary-action" disabled={!acknowledged} onClick={onRun}>執行 prototype simulation <ChevronRight size={17} /></button></div></article></aside></section></>;
}
